### 인증 페이지 요청
### 개발환경, 스테이징, 운영 환경에 따라서 다르게 처리할 수도 있고 변수를 다르게 사용할 수도 있다.


GET http://localhost:8090/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjc2OTYyNjcwfQ.VTgYKX9EubvvxLLHxjBXGr1sigV3OXQcoCRP2jD5g9M