### 인증 페이지 요청
### 개발환경, 스테이징, 운영 환경에 따라서 다르게 처리할 수도 있고 변수를 다르게 사용할 수도 있다.


GET http://localhost:8090/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjc4MzM4NjI0fQ.mIblOaf8fEQuNts-_vmvn0F8FzKT0dNZljkzQxScaSE

### 회원가입
POST http://localhost:8090/auth/signup
Content-Type: application/json

{
  "name": "test123123",
  "password": "mino123123s",
  "email": "minos1231232@naver.com"
}